title: Joseph M. Flores
#logo: /assets/img/logo.png
description: Data Analyst | Academic Specialist (Mathematics & Statistics) | Content Developer (Math & Stat)
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
