title: Joseph M. Flores
logo: docs/assets/Profile pic.png
description: Data Analyst | Academic Specialist (Mathematics & Statistics) | Content Developer (Math & Stat)
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
